apiVersion: v1
kind: Pod
metadata:
  name: api1
  labels:
    name: api1
spec:
  containers:
  - name: api1
    image: task1/api1
    imagePullPolicy: Never
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
