version: '3'
services:
  pythonapp:
    build: .
    # labels:
    #   kompose.service.type: LoadBalancer
    # container_name: pythonapp
    ports:
      - '5000:5000'
    depends_on: 
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass 
      POSTGRES_DB: mydb 
    ports:
      - 5432:5432
