apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: bXl1c2Vy
  password: bXlwYXNz
  connectionstring: aG9zdD1wb3N0Z3JlcyBkYm5hbWU9bXlkYiB1c2VyPW15dXNlciBwYXNzd29yZD1teXBhc3MgcG9ydD01NDMy
  database: bXlkYg==
